//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Calcular", ReplyAction="http://tempuri.org/IService1/CalcularResponse")]
        Servidor1.RespuestaCalculo Calcular(Servidor1.PeticionCalculo peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcularAsync", ReplyAction="http://tempuri.org/IService1/CalcularAsyncResponse")]
        Servidor1.RespuestaCalculo CalcularAsync(Servidor1.PeticionCalculo peticion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Cliente.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Cliente.ServiceReference1.IService1>, Cliente.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Servidor1.RespuestaCalculo Calcular(Servidor1.PeticionCalculo peticion) {
            return base.Channel.Calcular(peticion);
        }
        
        public Servidor1.RespuestaCalculo CalcularAsync(Servidor1.PeticionCalculo peticion) {
            return base.Channel.CalcularAsync(peticion);
        }
    }
}
